### ISSUE TITLE
Get release info for specific territory

### ISSUE THREAD

**Issue by GeorgNation** [miqwit/dedex#27]
How do I get information about releases, tracks and other files for individual regions? For example one track (although it can be both a file and a release) contains information for Worldwide and US regions, how to get the release for US?

**Comment by miqwit** [comment]
Hello @GeorgNation. 
You closed this issue so I guess you found a solution. I give an answer here for reference to other users.

Foreach Simple Entity, there is an access to a function `getDetailsByTerritory($element, string $type, string $territory = "worldwide")` where you can get information for a given territory (worldwide by default).

Note that you need to know the territory you are looking for. If the territory is missing for this element, an \Exception will be raised (in this case you can catch it and fallback on Worldwide if you wish).
