### ISSUE TITLE
ERN 4.1: No functions found for this tag: Party. Path is NewReleaseMessage,PartyList

### ISSUE THREAD

**Issue by ignacioalles** [miqwit/dedex#4]
There is an error while parsing a message `PartyList` node in NewReleaseMessage using ERN 4.1 spec.
Error message is:
> No functions found for this tag: Party. Path is NewReleaseMessage,PartyList

and the reason is that it seems an intermediate class `PartyListType` is required between NewReleaseMessage and PartyType.

Message looks like:
```
<ern:NewReleaseMessage 
   xmlns:ern="http://ddex.net/xml/ern/41"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://ddex.net/xml/ern/41 release-notification.xsd"
   ReleaseProfileVersionId="Audio" LanguageAndScriptCode="en">
   <MessageHeader>
   [....]
   </MessageHeader>
   <PartyList>
      <Party>
         <PartyReference>PSaekoShu</PartyReference>
         <PartyName>
            <FullName>Saeko Shu</FullName>
            <FullNameIndexed>Shu, Saeko</FullNameIndexed>
         </PartyName>
         <PartyName LanguageAndScriptCode="ja-Jpan">
            <FullName>しゅうさえこ</FullName>
         </PartyName>
      </Party>
      <Party>
         <PartyReference>PEMI</PartyReference>
         <PartyName>
            <FullName>EMI MUSIC JAPAN INC.</FullName>
         </PartyName>
      </Party>
   </PartyList>
   <ResourceList>
   [....]
```
Here is [some documentation](https://kb.ddex.net/pages/viewpage.action?pageId=11601394) explaining the addition in ERN-4

I can make a pull request if you'd like.

**Comment by miqwit** [comment]
As an additional note, I am not (yet) keen to approve your PR, because the entities are automatically generated by the tool [xsd2php](https://github.com/goetas-webservices/xsd2php), hence I don't want to modify them manually, but rather understand why it's not parsed properly.

**Comment by ignacioalles** [comment]
Sorry for the late reply. I can confirm it works fine with our testing files.
